/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-05-03 02:50:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.bbs;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("	<h1>자유 게시판.....</h1>\r\n");
      out.write("	<div class=\"row\"></div>\r\n");
      out.write("	<div class=\"col-6 col-md-4 col-lg-3 mb-2\">\r\n");
      out.write("		<form name=\"frm\">\r\n");
      out.write("			<div class=\"input-group\">\r\n");
      out.write("				<input  name=\"query\" class=\"form-control\">\r\n");
      out.write("				<button class=\"btn btn-info\">검색</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div>\r\n");
      out.write("			<span id=\"total\"></span>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"col text-end mb-2\" id=\"div_write\">\r\n");
      out.write("		<a href=\"/bbs/insert\" class=\"btn btn-primary btn-sm px-3\"> 글쓰기</a>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"div_bbs\"></div>\r\n");
      out.write("	<!-- 밑에 스크립드들은 데이터출력을 위한 도구일뿐 결국 데이터는 여기에 들어오는것. -->\r\n");
      out.write("	<div id=\"pagination\" class=\"pagination justify-content-center mt-5\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script id=\"temp_bbs\" type=\"x-handlebars-template\">\r\n");
      out.write("    <table class=\"table table-bordered table-dark\" style =\"text-align: center;\">\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>번호</td>\r\n");
      out.write("		<td>제목</td>\r\n");
      out.write("		<td>작성자</td>\r\n");
      out.write("		<td>작성일</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        {{#each .}}\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>{{bid}}</td>\r\n");
      out.write("                <td><a href=\"/bbs/read?bid={{bid}}\" style = \"text-decoration : none; color: white;\">{{title}}</td></a> <!-- 데이터가 넘어가는 링크를 걸어준다. -->\r\n");
      out.write("                <td>{{uname}}({{writer}})</td>\r\n");
      out.write("                <td>{{bdate}}</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        {{/each}}\r\n");
      out.write("    </table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script> //ajax은 스크립트에서 쓴다.\r\n");
      out.write("	let page = 1; //시작페이지설정해주기 \r\n");
      out.write("	let size = 5;\r\n");
      out.write("	let query =\"\";\r\n");
      out.write("	\r\n");
      out.write("	$(frm).on(\"submit\", function(e){\r\n");
      out.write("		e.preventDefault();\r\n");
      out.write("		query=$(frm.querey).val();\r\n");
      out.write("		alert(query);\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	getData();\r\n");
      out.write(" 	function getData() { //함수로 쓴이유는 여러번 해야하기때문에 \r\n");
      out.write(" 		$.ajax({ //데이터 호출시 ajax을 함수로 쓴다. \r\n");
      out.write("           		type: \"get\",\r\n");
      out.write("           	 	url: \"/bbs/list.json\", // 로컬서버는 ~3000까지는 생략가능 \r\n");
      out.write("           	 	dataType: \"json\",\r\n");
      out.write("           	 	data:{page, size, query},\r\n");
      out.write("           		success: function (data) { //url의 데이터가 여기로 들어감 \r\n");
      out.write("                		// alert(\"성공~\");\r\n");
      out.write("                		const temp = Handlebars.compile($(\"#temp_bbs\").html()); //아이디가 tempPosts인걸 html로 compile해서 temp에 저장 \r\n");
      out.write("                		$(\"#div_bbs\").html(temp(data)); // temp에 data를 넣고  divPosts에 출력   \r\n");
      out.write("            	}\r\n");
      out.write("        	});\r\n");
      out.write("    	};\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div class=\"col text-end\" id=\"divWrite\" > <!-- 아무튼 div안에 넣어야 만지기가 편하다. -->\r\n");
      out.write("        <a href=\"/bbs/insert\"><button class=\"btn btn-secondary\">글쓰기 </button></a> <!--누르면 a태그의 지정된 곳으로 가자 -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script> //글쓰기 보이기 안보이기 아이템을 안가져와도 되는이유는 메뉴에서 이미 가져오기때문이다.  //기본으로 숨겨놓고 아이디가 있으면 보이고 없으면 숨기기 한것.\r\n");
      out.write("    if (uid) {\r\n");
      out.write("        $(\"#divWrite\").show();\r\n");
      out.write("    }//그러니까 else가 사실 피료없다.  근데 jsp에서는 있어야 한다. \r\n");
      out.write("     else{\r\n");
      out.write("         $(\"#divWrite\").hide();\r\n");
      out.write("     }\r\n");
      out.write("     getTotal();\r\n");
      out.write("     function getTotal(){\r\n");
      out.write("    	 $.ajax({\r\n");
      out.write("    		 type:\"get\",\r\n");
      out.write("    		 url:\"/bbs/total\",\r\n");
      out.write("    		data:{query},\r\n");
      out.write(" 		 success:function(data){\r\n");
      out.write(" 			if(data ==0){\r\n");
      out.write(" 				alert(\"검색내용 없네요.\");\r\n");
      out.write(" 				$(frm.query).val(\"\");\r\n");
      out.write(" 			}else{\r\n");
      out.write(" 			const totalPage=Math.ceil(data/size);\r\n");
      out.write("            	$(\"#pagination\").twbsPagination(\"changeTotalPages\", totalPage, page);\r\n");
      out.write("            	$(\"#total\").html(\"검색수 :\" + data + \"건\");\r\n");
      out.write(" 			 }   \r\n");
      out.write(" 		}\r\n");
      out.write("    	 });	\r\n");
      out.write("     }\r\n");
      out.write("     //페이지네이션 출력\r\n");
      out.write("     $('#pagination').twbsPagination({\r\n");
      out.write("         totalPages:100, \r\n");
      out.write("         visiblePages: 10, \r\n");
      out.write("         startPage : 1,\r\n");
      out.write("         initiateStartPageClick: false, \r\n");
      out.write("         first:'<i>처음</i>', \r\n");
      out.write("         prev :'<i>이전</i>',\r\n");
      out.write("         next :'<i>다음</i>',\r\n");
      out.write("         last :'<i>마지막</i>',\r\n");
      out.write("         onPageClick: function (event, clickPage) {\r\n");
      out.write("             page=clickPage; \r\n");
      out.write("             getData();\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
